// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync-go-sdk/internal"
)

type UploadFileResponse struct {
	Message string `json:"message" url:"message"`
	S3Url   string `json:"s3_url" url:"s3_url"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UploadFileResponse) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UploadFileResponse) GetS3Url() string {
	if u == nil {
		return ""
	}
	return u.S3Url
}

func (u *UploadFileResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UploadFileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UploadFileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UploadFileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UploadFileResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UploadFileRequest struct {
	File interface{} `json:"file,omitempty" url:"-"`
}
