// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync-go-sdk/sdk/internal"
)

type CreateRoleRequest struct {
	Name               string  `json:"name" url:"-"`
	CanEdit            bool    `json:"can_edit" url:"-"`
	CanView            bool    `json:"can_view" url:"-"`
	HaveApiAccess      bool    `json:"have_api_access" url:"-"`
	HaveBillingOptions bool    `json:"have_billing_options" url:"-"`
	HaveWebhookAccess  bool    `json:"have_webhook_access" url:"-"`
	IsAdmin            bool    `json:"is_admin" url:"-"`
	Color              *string `json:"color,omitempty" url:"-"`
}

type RoleStatsResponse struct {
	AdminAccessCount   float64 `json:"admin_access_count" url:"admin_access_count"`
	BillingAccessCount float64 `json:"billing_access_count" url:"billing_access_count"`
	ApiAccessCount     float64 `json:"api_access_count" url:"api_access_count"`
	WebhookAccessCount float64 `json:"webhook_access_count" url:"webhook_access_count"`
	ViewAccessCount    float64 `json:"view_access_count" url:"view_access_count"`
	EditAccessCount    float64 `json:"edit_access_count" url:"edit_access_count"`
	TotalRoles         float64 `json:"total_roles" url:"total_roles"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RoleStatsResponse) GetAdminAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.AdminAccessCount
}

func (r *RoleStatsResponse) GetBillingAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.BillingAccessCount
}

func (r *RoleStatsResponse) GetApiAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.ApiAccessCount
}

func (r *RoleStatsResponse) GetWebhookAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.WebhookAccessCount
}

func (r *RoleStatsResponse) GetViewAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.ViewAccessCount
}

func (r *RoleStatsResponse) GetEditAccessCount() float64 {
	if r == nil {
		return 0
	}
	return r.EditAccessCount
}

func (r *RoleStatsResponse) GetTotalRoles() float64 {
	if r == nil {
		return 0
	}
	return r.TotalRoles
}

func (r *RoleStatsResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RoleStatsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RoleStatsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RoleStatsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RoleStatsResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RolesResponse = []*RoleResponse
