// Code generated by Fern. DO NOT EDIT.

package authentication

import (
	context "context"
	envsyncgosdk "github.com/EnvSync-Cloud/envsync-go-sdk"
	core "github.com/EnvSync-Cloud/envsync-go-sdk/core"
	internal "github.com/EnvSync-Cloud/envsync-go-sdk/internal"
	option "github.com/EnvSync-Cloud/envsync-go-sdk/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Retrieve the current authenticated user's information and their organization details
func (c *Client) Whoami(
	ctx context.Context,
	opts ...option.RequestOption,
) (*envsyncgosdk.WhoAmIResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"http://localhost:8600",
	)
	endpointURL := baseURL + "/api/auth/me"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		500: func(apiError *core.APIError) error {
			return &envsyncgosdk.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *envsyncgosdk.WhoAmIResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
